@startuml

actor "Big Brother" as bigbro
actor farmer as farmer 
boundary View as view
control Controller as controller
entity Model as model



farmer -> view : Click Farming Report Page link
activate view
view -> controller: Authentication of eligibility
activate controller

alt farmer eligible

    controller -> model: Request Page Info
    deactivate controller
    activate model
    model --> controller: Return Page Info
    deactivate model
    activate controller
    controller --> view: Display Page Info
    deactivate controller

    view -> farmer: Request farming report input
    activate controller
    
else farmer is ineligible
    controller --> view: Farmer is ineligible
    deactivate controller
    view -> farmer: Display error message
end

farmer --> view: Provide farming report inputs
view -> controller: Process farming report inputs
activate controller
controller --> view: Display farming report inputs
deactivate controller
view -> farmer: Confirm and send farming report?

alt farmer sent the report

    farmer --> view: Farmer confirms and sends the report
    view -> controller: handle sent farmer report
    activate controller
    controller -> model: update farming report database
    deactivate controller
    activate model
    model --> controller: confirm changes
    deactivate model
    activate controller
    controller --> view: update page details
    deactivate controller
    view -> farmer: Display updated farming report page
else farmer cancels
    farmer --> view: Farmer cancels sending the report
    view -> controller: Request previous farming report page data
    activate controller
    controller --> view: Return previous farming report page data
    deactivate controller
    view -> farmer: Display farming report page
end

bigbro -> view: Click farming report page link
view -> controller: Request for farming report page information
activate controller
controller -> model: Manage request
deactivate controller
activate model
model --> controller: Return farming report page information
deactivate model
activate controller
controller --> view: Display farming report page information
deactivate controller
view -> bigbro: Is the farming report valid?
bigbro --> view: rejects or approves farming report
view -> controller: handle farming report verification
activate controller
controller -> model: update farming stage of farmer
deactivate controller
activate model
model --> controller: return updated farming report information
deactivate model
activate controller
controller --> view: display updated farming report page
deactivate controller
view -> farmer: Notify farmer who reported


    










@enduml