@startwbs

* Anikultura System

**_ A

*** 1. Authenticate
****_ 1.1. Login to Account
****_ 1.2. Logout from Account

*** 2. Manage User
****_ 2.1. Create User Account
*****_ 2.1.1. Create Farmer Profile
*****_ 2.1.2. Create Big Brother Profile
*****_ 2.1.3. Create Admin Profile
****_ 2.2. Read User Information
****_ 2.3. Edit User Information
****_ 2.4. Delete User Account

*** 3. Manage Batch
****_ 3.1. Create Batch
*****_ 3.1.1. Assign Batch in a Site
****_ 3.2. Read Batch Information
****_ 3.3. Edit Batch Information
****_ 3.4. Delete Batch

**_ B
    
*** 4. Manage Farmland
****_ 4.1. Create Farmland
*****_ 4.1.1. Assign Farmland in a Batch
****_ 4.2. Assign Farmer in a Farmland
****_ 4.3. Read Farmland Information
****_ 4.4. Edit Farmland Information
****_ 4.5. Delete Farmland

*** 5. Manage Crop Type
****_ 5.1. Create Crop Type
****_ 5.2. Read Crop Type Information
****_ 5.3. Edit Crop Type Information
****_ 5.4. Delete Crop Type

**_ C

*** 6. Manage Site
****_ 6.1. Create Site
****_ 6.2. Read Site Information
****_ 6.3. Edit Site Information
****_ 6.4. Delete Site

*** 7. Send Farming Report

*** 8. Verify Farming Report

*** 9. Read Farming Insight
****_ 9.1. Read Farming Report History
****_ 9.2. Read Selling Price of Crop
****_ 9.3. Read Estimated Profit
****_ 9.4. Read Estimated Yield

@endwbs
