@startuml

left to right direction

actor "SMFI Admin" as admin
actor "Farmer" as farmer

rectangle "Anikultura System" {
    usecase "Login to Account" as C1.1

    usecase "Manage User" as AD1
    usecase "Read User Information" as AD1.2

    usecase "Manage Batch" as AD2
    usecase "Read Batch Information" as AD2.2

    usecase "Manage Farmland" as AD3
    usecase "Read Farmland Information" as AD3.2

    usecase "Manage Crop Type" as AD4
    usecase "Read Crop Type Information" as AD4.2

    usecase "Manage Site" as AD5
    usecase "Read Site Information" as AD5.2

    usecase "Send Farming Report" as FD1
    usecase "Read Farming Insight" as FD2
    ' usecase "Read Farming Report History" as FD2.1
    ' usecase "Read Selling Price of Crop" as FD2.2
    ' usecase "Read Estimated Profit" as FD2.3
    ' usecase "Read Estimated Yield" as FD2.4
}

' Admin Usecases

admin -- AD1
AD1 <.. AD1.2 : <<extend>>

admin -- AD2
AD2 <.. AD2.2 : <<extend>>

admin -- AD3
AD3 <.. AD3.2 : <<extend>>

admin -- AD4
AD4 <.. AD4.2 : <<extend>>

admin -- AD5
AD5 <.. AD5.2 : <<extend>>


' Farmer Usecases
admin -- C1.1

admin -- FD2
FD1 -- farmer

FD1 .> FD2 : <<extend>>

' FD1 .> FD2 : <<extend>>
' FD2 <.. FD2.1 : <<extend>>
' FD2 <.. FD2.2 : <<extend>>
' FD2 <.. FD2.3 : <<extend>>
' FD2 <.. FD2.4 : <<extend>>

C1.1 -- farmer
AD1.2 -- farmer
AD2.2 -- farmer
AD3.2 -- farmer
AD4.2 -- farmer
AD5.2 -- farmer
FD2 -- farmer


@enduml
