@startuml

left to right direction

rectangle "Anikultura System" {
    actor "Big Brother" as bigbro
    actor "Admin" as admin
    actor "Farmer" as farmer

    rectangle "Anikultura Server" {
        usecase "Manage User" as AD1
        usecase "Manage Batch" as AD2
        usecase "Manage Farmland" as AD3
        usecase "Manage Crop Type" as AD4
        usecase "Manage Site" as AD5

        usecase "Verify Farming Report" as AD6
        usecase "Read Farming Insight" as FD3
    }

    rectangle "Anikultura Client" {
        usecase "Send Farming Report" as FD1
        usecase "Read Personal Farming Insight" as FD2
    }
}

' Admin Usecases

admin -- AD1
admin -- AD2
bigbro -- AD3
bigbro -- AD4
bigbro -- AD6
admin -- AD5

admin -|> bigbro

' Usecase Dependencies

AD5 <. AD2 : <<include>>
AD2 <. AD1 : <<include>>
AD1 <. AD3 : <<include>>

' Farming Report to Manage Dependencies
AD1 <. FD1 : <<include>>
AD3 <. FD1 : <<include>>
AD4 <. FD1 : <<include>>

' Farming Insight
bigbro -- FD3
FD3 .> AD6 : <<include>>
AD6 ..> FD1 : <<include>>

FD3 <|--- FD2

FD1 -- farmer
FD2 -- farmer

' FD1 .> FD2 : <<extend>>


@enduml
