@startwbs

* SMFI Paper Forms

** 1. Farmer Management
***_ 1.1. Register Farmer by Filling Out Paper Form

** 2. Report Management
***_ 2.1. Read Submitted Reports
***_ 2.2. Send Report by Filling Out Paper Form

@endwbs
