@startuml

|Big Brother|
start
note left: Manage batch

:Visit Batches page;

|System|
:Return a list of all created sites;
|Big Brother|

if (Is there an existing batch?) then (yes)
    :Read batch information;
    if (Is it still in use?) then (yes)
        :Edit batch information;
    else (no)
        :Delete batch;
    endif
else (no)
    :Create batch;
    :Assign batch in a site;
    :Assign seed allocations;
endif

|System|
:Validate changes;
if (Are the changes valid?) then (yes)
    :Accept changes;
    :Show success message;
else (no)
    :Reject changes;
    :Show error message;
    stop
endif

|Big Brother|
:Read batch information;

stop

@enduml
