@startuml

|Farmer|

start
note left
    System already has
    configured sites, batches,
    users, farmlands, and crop
    types.
endnote

|Farmer|
if (Is eligible to send?) then (Yes)
    :Provide farming inputs;
    :Send farming report;

    |Big Brother|
    :Verify farming report;

    if (Is the report valid?) then (Yes)
        :Approve report;
        |System|
        :Generate farming insights;
    else (No)
        |Big Brother|
        :Reject report;
    endif
    |System|
    :Notify farmer who reported;
else (No)
    |Farmer|
    stop
endif

|Farmer|
if (Has approved reports?) then (Yes)
    |Farmer|
    :Read personal farming insights;
else (No)
endif

stop

@enduml